# Generated by Django 3.0 on 2025-01-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('has_job', models.BooleanField(default=False)),
                ('is_happy', models.BooleanField(default=False)),
            ],
        ),
    ]
